[package]
name = "protonolysis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
eframe = "0.21.3"
itertools = "0.10.5"
